table _ISE
	lineageTag: ebe34707-d406-4b33-b3fa-de41043e824d

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: d5ae6109-e1a6-48ac-8aa5-c43fbc24ab55
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ISE Name'
		dataType: string
		lineageTag: 52ce5889-2cff-472b-9b47-32b00c5d8874
		summarizeBy: none
		sourceColumn: ISE Name

		annotation SummarizationSetBy = Automatic

	partition _ISE = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://avantcommunications1-my.sharepoint.com/personal/jochoa_goavant_net/Documents/PowerBI/Tables/Niko's%20Folder/Engineers%20by%20Month%20for%20SE%20Metrics.xlsx"), null, true),
				    ISE_Sheet = Source{[Item="ISE",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(ISE_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}, {"Column25", type text}, {"Column26", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"4/1/2022", type text}, {"5/1/2022", type text}, {"6/1/2022", type text}, {"7/1/2022", type text}, {"8/1/2022", type text}, {"9/1/2022", type text}, {"10/1/2022", type text}, {"11/1/2022", type text}, {"12/1/2022", type text}, {"1/1/2023", type text}, {"2/1/2023", type text}, {"3/1/2023", type text}, {"4/1/2023", type text}, {"5/1/2023", type text}, {"6/1/2023", type text}, {"7/1/2023", type text}, {"8/1/2023", type text}, {"9/1/2023", type text}, {"10/1/2023", type text}, {"11/1/2023", type text}, {"12/1/2023", type text}, {"1/1/2024", type text}, {"2/1/2024", type text}, {"3/1/2024", type text}, {"4/1/2024", type text}, {"5/1/2024", type text}}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Changed Type1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Removed Blank Rows", {}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "Date"}, {"Value", "ISE Name"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type2",{{"ISE Name", Text.Trim, type text}}),
				    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"ISE Name", Text.Clean, type text}})
				in
				    #"Cleaned Text"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

