table Calendar
	lineageTag: bc66abab-46dc-4e6d-976a-4bce4c34866c

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: cb6675f6-b2ed-4145-ab3d-a4ef99b58d7c
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: bed6ac1f-67ab-44f1-ac4c-6d7b730241ae
			defaultHierarchy: LocalDateTable_59275887-931c-42e8-bbc2-e30c40d78d00.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthNum
		dataType: int64
		formatString: 0
		lineageTag: be72cb77-9805-43fb-b739-a909e58f0b2c
		summarizeBy: sum
		sourceColumn: MonthNum

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: ec0eb003-a5e2-4b86-909f-33eee7c560ae
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthLong
		dataType: string
		lineageTag: ac6c5999-d553-41a6-9740-3d73ead0aa0a
		summarizeBy: none
		sourceColumn: MonthLong

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 21d5dffd-3ba5-4175-986b-fbc260369ce6
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 645ccefd-73f6-43de-9806-f5f74a345268
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	column 'Start Date of Week'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 83e000e5-0892-43e3-a582-0d94b6a227dd
		summarizeBy: none
		sourceColumn: Start Date of Week

		variation Variation
			isDefault
			relationship: 678493bd-fac1-40ef-86b5-10e8cb99f7df
			defaultHierarchy: LocalDateTable_7809a66c-85a3-40ad-aa1b-8e3bb7925b7b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FiscalMonthNum
		dataType: double
		lineageTag: c4837eaf-3730-4914-a2be-e232409fe82b
		summarizeBy: sum
		sourceColumn: FiscalMonthNum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FiscalMonth
		dataType: string
		lineageTag: 41282230-66e1-4c6e-bda6-9d74d7690d1c
		summarizeBy: none
		sourceColumn: FiscalMonth

		annotation SummarizationSetBy = Automatic

	column FiscalMonthLong
		dataType: string
		lineageTag: 30347c70-1f6a-4837-b317-e357fd55df2c
		summarizeBy: none
		sourceColumn: FiscalMonthLong

		annotation SummarizationSetBy = Automatic

	column FiscalQuarter
		dataType: string
		lineageTag: 226f8a13-cf9e-4723-9c17-e081bbe0ceff
		summarizeBy: none
		sourceColumn: FiscalQuarter

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: string
		lineageTag: 86e2a2a3-8c76-4107-b1de-d9d3bc94faa0
		summarizeBy: none
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column CurMonthOffset
		dataType: int64
		formatString: 0
		lineageTag: 9dcbfae5-a8d4-4dc8-96e6-eea6e72bffc9
		summarizeBy: none
		sourceColumn: CurMonthOffset

		annotation SummarizationSetBy = User

	column CurQuarterOffset
		dataType: int64
		formatString: 0
		lineageTag: 4f13f585-cc42-40ed-b074-4084ee1c6c2d
		summarizeBy: none
		sourceColumn: CurQuarterOffset

		annotation SummarizationSetBy = User

	column CurYearOffset
		dataType: int64
		formatString: 0
		lineageTag: 1af62496-337e-45c1-82e7-1907299a7b0a
		summarizeBy: none
		sourceColumn: CurYearOffset

		annotation SummarizationSetBy = User

	column FutureDate
		dataType: string
		lineageTag: 22743253-a1a1-41b2-a7da-b1236987c8cd
		summarizeBy: none
		sourceColumn: FutureDate

		annotation SummarizationSetBy = Automatic

	column CurFiscalYearOffset
		dataType: int64
		formatString: 0
		lineageTag: b84e825c-c589-407e-b087-d8fec64bd482
		summarizeBy: none
		sourceColumn: CurFiscalYearOffset

		annotation SummarizationSetBy = User

	column MonthYearNum
		dataType: int64
		formatString: 0
		lineageTag: c28340c6-f4a3-4f3f-91fa-57ab16e1237d
		summarizeBy: sum
		sourceColumn: MonthYearNum

		annotation SummarizationSetBy = Automatic

	column MonthYear
		dataType: string
		lineageTag: c29be102-f189-4eb5-9d1c-7d5b166e4f44
		summarizeBy: none
		sourceColumn: MonthYear

		annotation SummarizationSetBy = Automatic

	column MonthYearLong
		dataType: string
		lineageTag: c79dca90-5567-40b6-87b2-331a2e342533
		summarizeBy: none
		sourceColumn: MonthYearLong

		annotation SummarizationSetBy = Automatic

	column WeekdayNum
		dataType: int64
		formatString: 0
		lineageTag: 0a2d4b81-fa5a-4fea-ada9-c8052900f803
		summarizeBy: sum
		sourceColumn: WeekdayNum

		annotation SummarizationSetBy = Automatic

	column Weekday
		dataType: string
		lineageTag: 21b32e8e-d45a-40f0-b67d-b5f8684ddda7
		summarizeBy: none
		sourceColumn: Weekday

		annotation SummarizationSetBy = Automatic

	column WeekdayWeekend
		dataType: string
		lineageTag: 28cd5265-a04e-45db-998c-17fe377bd256
		summarizeBy: none
		sourceColumn: WeekdayWeekend

		annotation SummarizationSetBy = Automatic

	column WeekSequenceNum
		dataType: double
		lineageTag: 1d2578d1-56eb-4498-96e6-f174511d1c12
		summarizeBy: sum
		sourceColumn: WeekSequenceNum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CurWeekOffset
		dataType: int64
		formatString: 0
		lineageTag: 3c3f3c38-addd-491a-92ce-a52d53888a92
		summarizeBy: none
		sourceColumn: CurWeekOffset

		annotation SummarizationSetBy = User

	column WeekNumber
		dataType: int64
		formatString: 0
		lineageTag: f3d4fa2c-bd3c-451f-8eb6-c8fa08ea87ee
		summarizeBy: sum
		sourceColumn: WeekNumber

		annotation SummarizationSetBy = Automatic

	column FiscalWeek
		dataType: int64
		formatString: 0
		lineageTag: 88d684d4-f753-44e0-81db-66738d0a34b6
		summarizeBy: sum
		sourceColumn: FiscalWeek

		annotation SummarizationSetBy = Automatic

	partition Calendar = m
		mode: import
		source = ```
				let
				    /*
				    ****This Calendar was created and provided by Avi Singh****
				    ****This can be freely shared as long as this text comment is retained.****
				    http://www.youtube.com/PowerBIPro
				    www.LearnPowerBI.com by Avi Singh
				    */
				    #"LearnPowerBI.com by Avi Singh" = 1,
				    StartDate = #date(2009, 1, 1),
				    FiscalYearEndMonth = 3,
				    EndDate = Date.AddMonths(Date.EndOfYear(DateTime.Date(DateTime.FixedLocalNow())),FiscalYearEndMonth) /*was "#date(2017, 1, 1)" Updated on 201802027: hard Coded End of Year caused some formulas to break, switching to dynamic date*/,
				    //Used for 'Offset' Column calculations, you may Hard code CurrentDate for testing e.g. #date(2017,9,1)
				    CurrentDate = DateTime.Date(DateTime.FixedLocalNow()),
				    // Specify the last month in your Fiscal Year, e.g. if June is the last month of your Fiscal Year, specify 6
				
				    #"==SET PARAMETERS ABOVE==" = 1,
				    #"==Build Date Column==" = #"==SET PARAMETERS ABOVE==",
				    ListDates = List.Dates(StartDate, Number.From(EndDate - StartDate)+1, #duration(1,0,0,0)),
				    #"Converted to Table" = Table.FromList(ListDates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns as Date" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
				    // As far as Power BI is concerned, the 'Date' column is all that is needed :-) But we will continue and add a few Human-Friendly Columns
				    #"Changed Type to Date" = Table.TransformColumnTypes(#"Renamed Columns as Date",{{"Date", type date}}),
				    #"==Add Calendar Columns==" = #"Changed Type to Date",
				    #"Added Calendar MonthNum" = Table.AddColumn(#"==Add Calendar Columns==", "MonthNum", each Date.Month([Date]), Int64.Type),
				    #"Added Month Name" = Table.AddColumn(#"Added Calendar MonthNum", "Month", each Text.Start(Date.MonthName([Date]),3), type text),
				    #"Added Month Name Long" = Table.AddColumn(#"Added Month Name", "MonthLong", each Date.MonthName([Date]), type text),
				    #"Added Calendar Quarter" = Table.AddColumn(#"Added Month Name Long", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Calendar Year" = Table.AddColumn(#"Added Calendar Quarter", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Custom" = Table.AddColumn(#"Added Calendar Year", "Start Date of Week", each Date.StartOfWeek([Date])),
				    #"==Add Fiscal Calendar Columns==" = #"Added Custom",
				    #"Added FiscalMonthNum" = Table.AddColumn(#"==Add Fiscal Calendar Columns==", "FiscalMonthNum", each if [MonthNum] > FiscalYearEndMonth
				then [MonthNum] - FiscalYearEndMonth
				else [MonthNum] + (12 - FiscalYearEndMonth), type number),
				    #"Added FiscalMonth Name" = Table.AddColumn(#"Added FiscalMonthNum", "FiscalMonth", each [Month]),
				    #"Added FiscalMonth Name Long" = Table.AddColumn(#"Added FiscalMonth Name", "FiscalMonthLong", each [MonthLong]),
				    #"Added FiscalQuarter" = Table.AddColumn(#"Added FiscalMonth Name Long", "FiscalQuarter", each "FQ" & Text.From(Number.RoundUp([FiscalMonthNum] / 3,0))),
				    #"Added FiscalYear" = Table.AddColumn(#"Added FiscalQuarter", "FiscalYear", each "FY" & 
				Text.End(
				  Text.From(
				    if [MonthNum] > FiscalYearEndMonth
				    then [Year] + 1
				    else [Year]
				  )
				  , 2
				)),
				
				    #"==Add Calendar Date Offset Columns==" = #"Added FiscalYear",
				    // Can be used to for example to show the past 3 months(CurMonthOffset = 0, -1, -2)
				    #"Added CurMonthOffset" = Table.AddColumn(#"==Add Calendar Date Offset Columns==", "CurMonthOffset", each ( Date.Year([Date]) - Date.Year(CurrentDate) ) * 12
				+ Date.Month([Date]) - Date.Month(CurrentDate), Int64.Type),
				    // Can be used to for example to show the past 3 quarters (CurQuarterOffset = 0, -1, -2)
				    #"Added CurQuarterOffset" = Table.AddColumn(#"Added CurMonthOffset", "CurQuarterOffset", each /*Year Difference*/
				       ( Date.Year([Date]) - Date.Year(CurrentDate) )*4
				       /*Quarter Difference*/
				      + Number.RoundUp(Date.Month([Date]) / 3) 
				      - Number.RoundUp(Date.Month(CurrentDate) / 3),
				Int64.Type),
				    // Can be used to for example to show the past 3 years (CurYearOffset = 0, -1, -2)
				    #"Added CurYearOffset" = Table.AddColumn(#"Added CurQuarterOffset", "CurYearOffset", each Date.Year([Date]) - Date.Year(CurrentDate), Int64.Type),
				    // Can be used to for example filter out all future dates
				    #"Added FutureDate Flag" = Table.AddColumn(#"Added CurYearOffset", "FutureDate", each if [Date] > CurrentDate then "Future" else "Past" ),
				    // FiscalYearOffset is the only Offset that is different.
				    // FiscalQuarterOffset = is same as CurQuarterOffset
				    // FiscalMonthOffset = is same as CurMonthOffset
				    #"==Add FiscalYearOffset==" = #"Added FutureDate Flag",
				    #"Filtered Rows to CurrentDate" = Table.SelectRows(#"==Add FiscalYearOffset==", each ([Date] = CurrentDate)),
				    CurrentFiscalYear = #"Filtered Rows to CurrentDate"{0}[FiscalYear],
				    #"Continue...Orig Table" = #"==Add FiscalYearOffset==",
				    #"Added CurFiscalYearOffset" = Table.AddColumn(#"Continue...Orig Table", "CurFiscalYearOffset", each Number.From(Text.Range([FiscalYear],2,2)) - 
				Number.From(Text.Range(CurrentFiscalYear,2,2))
				/*Extract the numerical portion, e.g. FY18 = 18*/),
				    #"==Add General Columns==" = #"Added CurFiscalYearOffset",
				    // Used as 'Sort by Column' for MonthYear columns
				    #"Added MonthYearNum" = Table.AddColumn(#"==Add General Columns==", "MonthYearNum", each [Year]*100 + [MonthNum] /*e.g. Sep-2016 would become 201609*/, Int64.Type),
				    #"Added MonthYear" = Table.AddColumn(#"Added MonthYearNum", "MonthYear", each [Month] & "-" & Text.End(Text.From([Year]),2)),
				    #"Added MonthYearLong" = Table.AddColumn(#"Added MonthYear", "MonthYearLong", each [Month] & "-" & Text.From([Year])),
				    #"Added WeekdayNum" = Table.AddColumn(#"Added MonthYearLong", "WeekdayNum", each Date.DayOfWeek([Date]), Int64.Type),
				    #"Added Weekday Name" = Table.AddColumn(#"Added WeekdayNum", "Weekday", each Text.Start(Date.DayOfWeekName([Date]),3), type text),
				    #"Added WeekdayWeekend" = Table.AddColumn(#"Added Weekday Name", "WeekdayWeekend", each if [WeekdayNum] = 0 or [WeekdayNum] = 6
				then "Weekend"
				else "Weekday"),
				    #"==Improve Ultimate Table" = #"Added WeekdayWeekend",
				    #"----Add WeekSequenceNum----" = #"==Improve Ultimate Table",
				    #"Filtered Rows Sundays Only (Start of Week)" = Table.SelectRows(#"----Add WeekSequenceNum----", each ([WeekdayNum] = 0)),
				    #"Added Index WeekSequenceNum" = Table.AddIndexColumn(#"Filtered Rows Sundays Only (Start of Week)", "WeekSequenceNum", 2, 1),
				    #"Merged Queries Ultimate Table to WeekSequenceNum" = Table.NestedJoin(#"==Improve Ultimate Table",{"Date"},#"Added Index WeekSequenceNum",{"Date"},"Added Index WeekNum",JoinKind.LeftOuter),
				    #"Expanded Added Index WeekNum" = Table.ExpandTableColumn(#"Merged Queries Ultimate Table to WeekSequenceNum", "Added Index WeekNum", {"WeekSequenceNum"}, {"WeekSequenceNum"}),
				    // somehow it ends up being unsorted after Expand Column, should not matter for the end table, but makes it harder to debug and check everything is correct. Thus sorting it.
				    #"ReSorted Rows by Date" = Table.Sort(#"Expanded Added Index WeekNum",{{"Date", Order.Ascending}}),
				    #"Filled Down WeekSequenceNum" = Table.FillDown(#"ReSorted Rows by Date",{"WeekSequenceNum"}),
				    #"Replaced Value WeekSequenceNum null with 1" = Table.ReplaceValue(#"Filled Down WeekSequenceNum",null,1,Replacer.ReplaceValue,{"WeekSequenceNum"}),
				    #"----WeekSequenceNum Complete----" = #"Replaced Value WeekSequenceNum null with 1",
				    Current_WeekSequenceNum = #"----WeekSequenceNum Complete----"{[Date = CurrentDate]}?[WeekSequenceNum],
				    #"Added Custom CurWeekOffset" = Table.AddColumn(#"----WeekSequenceNum Complete----", "CurWeekOffset", each [WeekSequenceNum] - Current_WeekSequenceNum, Int64.Type),
				    #"Added Custom WeekNumber" = Table.AddColumn(#"Added Custom CurWeekOffset", "WeekNumber", each Date.WeekOfYear([Date], Day.Sunday)),
				    #"Changed Type to WholeNumber" = Table.TransformColumnTypes(#"Added Custom WeekNumber",{{"WeekNumber", Int64.Type}}),
				    #"Inserted Replaced Text" = Table.AddColumn(#"Changed Type to WholeNumber", "Replaced Text", each Text.Replace([FiscalYear], "FY", "20"), type text),
				    #"Changed Type" = Table.TransformColumnTypes(#"Inserted Replaced Text",{{"Replaced Text", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Replaced Text", "FYNumber"}}),
				    #"AddedFiscalWeek" = Table.AddColumn(#"Renamed Columns", "FiscalWeek", each if [WeekNumber] < Date.WeekOfYear(#date([FYNumber], 4, 1))
				then [WeekNumber] + 53 - Date.WeekOfYear(#date([FYNumber], 4, 1)) + 1
				else [WeekNumber] - Date.WeekOfYear(#date([FYNumber], 4, 1)) + 1, Int64.Type),
				    #"Removed Columns" = Table.RemoveColumns(AddedFiscalWeek,{"FYNumber"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"Start Date of Week", type date}, {"Quarter", type text}, {"FiscalMonth", type text}, {"FiscalMonthLong", type text}, {"FiscalQuarter", type text}, {"FiscalYear", type text}, {"FutureDate", type text}, {"CurFiscalYearOffset", Int64.Type}, {"MonthYear", type text}, {"MonthYearLong", type text}, {"WeekdayWeekend", type text}})
				
				in
				    #"Changed Type1"
				```

	annotation PBI_ResultType = Table

