DEFINE
	VAR __DS0FilterTable = 
		FILTER(
			KEEPFILTERS(VALUES('Calendar'[FiscalYear])),
			NOT('Calendar'[FiscalYear] IN {BLANK()})
		)

	VAR __DS0FilterTable2 = 
		FILTER(
			KEEPFILTERS(VALUES('Channel Managers'[Channel Manager])),
			NOT(
				'Channel Managers'[Channel Manager] IN {"Brandon Ciancio",
					"Chip Hoisington",
					"GearsCRM",
					"General Account",
					"JP Tucker",
					"Matt Menoyo",
					"Trident",
					BLANK()}
			)
		)

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			'Channel Managers'[RVP],
			'Partners'[Partner],
			__DS0FilterTable,
			__DS0FilterTable2,
			"v_TotalAvantCost", '_Local Measures'[_TotalAvantCost],
			"v_MasterPercentile", '_Local Measures'[_MasterPercentile]
		)

	VAR __OverlappingPointsSampleLimitOperatorMinMax = 
		GROUPBY(
			__DS0Core,
			"Maxv_TotalAvantCost", MAXX(CURRENTGROUP(), [v_TotalAvantCost]),
			"Minv_TotalAvantCost", MINX(CURRENTGROUP(), [v_TotalAvantCost])
		)

	VAR __M0Min = 
		SELECTCOLUMNS(
			KEEPFILTERS(__OverlappingPointsSampleLimitOperatorMinMax),
			"Minv_TotalAvantCost", [Minv_TotalAvantCost]
		)

	VAR __M0Max = 
		SELECTCOLUMNS(
			KEEPFILTERS(__OverlappingPointsSampleLimitOperatorMinMax),
			"Maxv_TotalAvantCost", [Maxv_TotalAvantCost]
		)

	VAR __M0CanApplyLog = AND(__M0Min > 0, __M0Max > 0)

	VAR __M0CanApplyNegativeLog = AND(__M0Min < 0, __M0Max < 0)

	VAR __DS0IntersectionCount = CALCULATE(COUNTROWS(__DS0Core))

	VAR __DS0BodyOverlappingPointsSample = 
		SAMPLECARTESIANPOINTSBYCOVER(
			3500,
			__DS0Core,
			[v_MasterPercentile],
			IFERROR(
				IF(
					__M0CanApplyLog,
					Log10([v_TotalAvantCost]),
					IF(
						__M0CanApplyNegativeLog,
						-(Log10(-([v_TotalAvantCost]))),
						[v_TotalAvantCost]
					)
				),
				[v_TotalAvantCost]
			)
		)

EVALUATE
	ROW(
		"YTransformApplied", OR(__M0CanApplyLog, __M0CanApplyNegativeLog),
		"DS0IntersectionCount", __DS0IntersectionCount
	)

EVALUATE
	__DS0BodyOverlappingPointsSample

ORDER BY
	'Channel Managers'[RVP], 'Partners'[Partner]